# Generated by Django 5.2.8 on 2025-11-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("Art", "Art"),
                    ("Electronics", "Electronics"),
                    ("Furniture", "Furniture"),
                    ("Collectible", "Collectible"),
                ],
                default="Other",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Vendue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("duration_hours", models.PositiveIntegerField(default=24)),
                ("category", models.CharField(default="Other", max_length=100)),
                (
                    "attachment",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendue_attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
