# Generated by Django 4.2.26 on 2025-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auction_category_vendue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendue",
            name="duration_hours",
        ),
        migrations.AddField(
            model_name="vendue",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
